/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChildSafetyRouteImport } from './routes/child-safety'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as UProfileRouteImport } from './routes/u.profile'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as LiveStreamIdRouteImport } from './routes/live.$streamId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicMuxWebhookRouteImport } from './routes/api/public/mux/webhook'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildSafetyRoute = ChildSafetyRouteImport.update({
  id: '/child-safety',
  path: '/child-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const UProfileRoute = UProfileRouteImport.update({
  id: '/u/profile',
  path: '/u/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStreamIdRoute = LiveStreamIdRouteImport.update({
  id: '/live/$streamId',
  path: '/live/$streamId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMuxWebhookRoute = ApiPublicMuxWebhookRouteImport.update({
  id: '/api/public/mux/webhook',
  path: '/api/public/mux/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/child-safety': typeof ChildSafetyRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/earnings': typeof EarningsRoute
  '/guidelines': typeof GuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/live/$streamId': typeof LiveStreamIdRoute
  '/u/$username': typeof UUsernameRoute
  '/u/profile': typeof UProfileRoute
  '/live/': typeof LiveIndexRoute
  '/api/public/mux/webhook': typeof ApiPublicMuxWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/child-safety': typeof ChildSafetyRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/earnings': typeof EarningsRoute
  '/guidelines': typeof GuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/live/$streamId': typeof LiveStreamIdRoute
  '/u/$username': typeof UUsernameRoute
  '/u/profile': typeof UProfileRoute
  '/live': typeof LiveIndexRoute
  '/api/public/mux/webhook': typeof ApiPublicMuxWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/child-safety': typeof ChildSafetyRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/earnings': typeof EarningsRoute
  '/guidelines': typeof GuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/live/$streamId': typeof LiveStreamIdRoute
  '/u/$username': typeof UUsernameRoute
  '/u/profile': typeof UProfileRoute
  '/live/': typeof LiveIndexRoute
  '/api/public/mux/webhook': typeof ApiPublicMuxWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/activity'
    | '/auth'
    | '/campaigns'
    | '/child-safety'
    | '/contact'
    | '/discover'
    | '/dmca'
    | '/earnings'
    | '/guidelines'
    | '/privacy'
    | '/refunds'
    | '/search'
    | '/settings'
    | '/share'
    | '/terms'
    | '/upload'
    | '/wallet'
    | '/welcome'
    | '/live/$streamId'
    | '/u/$username'
    | '/u/profile'
    | '/live/'
    | '/api/public/mux/webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/activity'
    | '/auth'
    | '/campaigns'
    | '/child-safety'
    | '/contact'
    | '/discover'
    | '/dmca'
    | '/earnings'
    | '/guidelines'
    | '/privacy'
    | '/refunds'
    | '/search'
    | '/settings'
    | '/share'
    | '/terms'
    | '/upload'
    | '/wallet'
    | '/welcome'
    | '/live/$streamId'
    | '/u/$username'
    | '/u/profile'
    | '/live'
    | '/api/public/mux/webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/account-deletion'
    | '/activity'
    | '/auth'
    | '/campaigns'
    | '/child-safety'
    | '/contact'
    | '/discover'
    | '/dmca'
    | '/earnings'
    | '/guidelines'
    | '/privacy'
    | '/refunds'
    | '/search'
    | '/settings'
    | '/share'
    | '/terms'
    | '/upload'
    | '/wallet'
    | '/welcome'
    | '/live/$streamId'
    | '/u/$username'
    | '/u/profile'
    | '/live/'
    | '/api/public/mux/webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDeletionRoute: typeof AccountDeletionRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRoute
  ChildSafetyRoute: typeof ChildSafetyRoute
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRoute
  DmcaRoute: typeof DmcaRoute
  EarningsRoute: typeof EarningsRoute
  GuidelinesRoute: typeof GuidelinesRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  LiveStreamIdRoute: typeof LiveStreamIdRoute
  UUsernameRoute: typeof UUsernameRoute
  UProfileRoute: typeof UProfileRoute
  LiveIndexRoute: typeof LiveIndexRoute
  ApiPublicMuxWebhookRoute: typeof ApiPublicMuxWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child-safety': {
      id: '/child-safety'
      path: '/child-safety'
      fullPath: '/child-safety'
      preLoaderRoute: typeof ChildSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/profile': {
      id: '/u/profile'
      path: '/u/profile'
      fullPath: '/u/profile'
      preLoaderRoute: typeof UProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$streamId': {
      id: '/live/$streamId'
      path: '/live/$streamId'
      fullPath: '/live/$streamId'
      preLoaderRoute: typeof LiveStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mux/webhook': {
      id: '/api/public/mux/webhook'
      path: '/api/public/mux/webhook'
      fullPath: '/api/public/mux/webhook'
      preLoaderRoute: typeof ApiPublicMuxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDeletionRoute: AccountDeletionRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRoute,
  ChildSafetyRoute: ChildSafetyRoute,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRoute,
  DmcaRoute: DmcaRoute,
  EarningsRoute: EarningsRoute,
  GuidelinesRoute: GuidelinesRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  LiveStreamIdRoute: LiveStreamIdRoute,
  UUsernameRoute: UUsernameRoute,
  UProfileRoute: UProfileRoute,
  LiveIndexRoute: LiveIndexRoute,
  ApiPublicMuxWebhookRoute: ApiPublicMuxWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
